apiVersion: v1
kind: Service
metadata:
  name: apptest-svc
  labels:
    app: apptest
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9090
    protocol: TCP
    name: http
  selector:
    app: apptest