kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: app-test-s6
  labels:
    app: apptest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apptest
    spec:
      nodeName: ist-slave6
      containers:
      - image: docker.io/wy2745/java-app-test:1.0
        command: ["java","-jar","/home/test_app-1.0-SNAPSHOT.jar"]
        name: app-test-s6
        resources:
          limits:
            memory: "1Gi"
        ports:
        - containerPort: 9090
