apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress 
  #namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
        k8s-app: nginx-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: nginx-ingress-lb
    spec:
      nodeName: ist-slave2
      serviceAccountName: nginx-ingress-serviceaccount
      #serviceAccountName: heapster
      containers:
        - name: nginx-ingress-controller
          image: wy2745/nginx-ingress-controller:1.0
          args:
             - /nginx-ingress-controller
             - --default-backend-service=default/default-http-backend
             - --default-ssl-certificate=$(POD_NAMESPACE)/tls-certificate
          env:
             - name: POD_NAME
               valueFrom:
                 fieldRef:
                   fieldPath: metadata.name
             - name: POD_NAMESPACE
               valueFrom:
                 fieldRef:
                   fieldPath: metadata.namespace
          volumeMounts:
             - name: loadpath
               mountPath: /home/load
          ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
      volumes:
        - name: loadpath
          hostPath:
            path: /home/administrator/go/src/github.com/wy2745/ingress/tsung
